# Generated by Django 5.2 on 2025-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_medicaltest_testbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
