# Generated by Django 5.2 on 2025-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_medicine_medicineorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'Rocket'), ('dbbl', 'DBBL'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('cash', 'Cash')], default='bkash', max_length=20),
        ),
    ]
