# Generated by Django 5.2 on 2025-04-27 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_medicineorder_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='testbooking',
            name='notes',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'Rocket'), ('dbbl', 'DBBL'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('cash', 'Cash')], default='bkash', max_length=20),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('rocket', 'Rocket'), ('dbbl', 'DBBL'), ('visa', 'Visa'), ('mastercard', 'MasterCard'), ('cash', 'Cash')], default='bkash', max_length=20),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
