# Generated by Django 5.2 on 2025-04-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
